// This file is generated by generator.ts
public struct AudioInput: Codable {
  public let customSessionId: String?
  public let data: String
  public let type: String

  public init(customSessionId: String?, data: String, type: String) {
    self.customSessionId = customSessionId
    self.data = data
    self.type = type
  }
}
