// This file is generated by generator.ts
public struct AudioInput: Codable, Hashable {
  public let type: String
  public let customSessionId: String?
  public let data: String

  public init(
    customSessionId: String?,
    data: String
  ) {
    self.customSessionId = customSessionId
    self.data = data
    self.type = "audio_input"
  }
}
