// This file is generated by generator.ts
public struct AudioConfiguration: Codable {
  public let channels: Int
  public let encoding: AudioEncoding
  public let sampleRate: Int

  public init(channels: Int, encoding: AudioEncoding, sampleRate: Int) {
    self.channels = channels
    self.encoding = encoding
    self.sampleRate = sampleRate
  }
}
