// This file is generated by generator.ts
public struct BuiltinToolConfig: Codable, Hashable {
  public let name: BuiltInTool
  public let fallbackContent: String?

  public init(
    fallbackContent: String?,
    name: BuiltInTool
  ) {
    self.fallbackContent = fallbackContent
    self.name = name
  }
}
