// This file is generated by generator.ts
public struct ChatMessage: Codable {
  public let content: String?
  public let role: Role
  public let toolCall: ToolCallMessage?
  public let toolResult: TODO_UNIONOFREFS_TYPE?

  public init(
    content: String?, role: Role, toolCall: ToolCallMessage?, toolResult: TODO_UNIONOFREFS_TYPE?
  ) {
    self.content = content
    self.role = role
    self.toolCall = toolCall
    self.toolResult = toolResult
  }
}
