// This file is generated by generator.ts
public struct Context: Codable, Hashable {
  public let type: ContextType?
  public let text: String

  public init(
    text: String,
    type: ContextType?
  ) {
    self.text = text
    self.type = type
  }
}
