// This file is generated by generator.ts
public struct EviPostedTimeoutSpecs: Codable, Hashable {
  public let inactivity: Inactivity?
  public let maxDuration: MaxDuration?

  public init(
    inactivity: Inactivity?,
    maxDuration: MaxDuration?
  ) {
    self.inactivity = inactivity
    self.maxDuration = maxDuration
  }
}
