// This file is generated by generator.ts
public struct EviPostedConfigVersionDescription: Codable, Hashable {
  public let versionDescription: String?

  public init(versionDescription: String?) {
    self.versionDescription = versionDescription
  }
}
