// This file is generated by generator.ts
#if HUME_SERVER
  public struct EviPostedWebhookSpec: Codable, Hashable {
    public let url: String
    public let events: [PostedWebhookEventType]

    public init(
      url: String,
      events: [PostedWebhookEventType]
    ) {
      self.url = url
      self.events = events
    }
  }
#endif
