// This file is generated by generator.ts
public struct EviPostedEventMessageSpecs: Codable, Hashable {
  public let onNewChat: EviPostedEventMessageSpec?
  public let onInactivityTimeout: EviPostedEventMessageSpec?
  public let onMaxDurationTimeout: EviPostedEventMessageSpec?

  public init(
    onNewChat: EviPostedEventMessageSpec?,
    onInactivityTimeout: EviPostedEventMessageSpec?,
    onMaxDurationTimeout: EviPostedEventMessageSpec?
  ) {
    self.onNewChat = onNewChat
    self.onInactivityTimeout = onInactivityTimeout
    self.onMaxDurationTimeout = onMaxDurationTimeout
  }
}
