// This file is generated by generator.ts
public struct EviPostedEventMessageSpec: Codable, Hashable {
  public let enabled: Bool
  public let text: String?

  public init(
    enabled: Bool,
    text: String?
  ) {
    self.enabled = enabled
    self.text = text
  }
}
