// This file is generated by generator.ts
public struct EviPostedConfigPromptSpec: Codable, Hashable {
  public let id: String?
  public let version: Int?
  public let text: String?

  public init(
    id: String?,
    version: Int?,
    text: String?
  ) {
    self.id = id
    self.version = version
    self.text = text
  }
}
