// This file is generated by generator.ts
#if HUME_SERVER
  public struct EviPostedConfigVersion: Codable, Hashable {
    public let eviVersion: String
    public let versionDescription: String?
    public let prompt: EviPostedConfigPromptSpec?
    public let voice: EviVoiceRef?
    public let languageModel: EviPostedLanguageModel?
    public let ellmModel: EviPostedEllmModel?
    public let tools: [EviPostedUserDefinedToolSpec]?
    public let builtinTools: [EviPostedBuiltinTool]?
    public let eventMessages: EviPostedEventMessageSpecs?
    public let timeouts: EviPostedTimeoutSpecs?
    public let nudges: EviPostedNudgeSpec?
    public let webhooks: [EviPostedWebhookSpec]?

    public init(
      eviVersion: String,
      versionDescription: String?,
      prompt: EviPostedConfigPromptSpec?,
      voice: EviVoiceRef?,
      languageModel: EviPostedLanguageModel?,
      ellmModel: EviPostedEllmModel?,
      tools: [EviPostedUserDefinedToolSpec]?,
      builtinTools: [EviPostedBuiltinTool]?,
      eventMessages: EviPostedEventMessageSpecs?,
      timeouts: EviPostedTimeoutSpecs?,
      nudges: EviPostedNudgeSpec?,
      webhooks: [EviPostedWebhookSpec]?
    ) {
      self.eviVersion = eviVersion
      self.versionDescription = versionDescription
      self.prompt = prompt
      self.voice = voice
      self.languageModel = languageModel
      self.ellmModel = ellmModel
      self.tools = tools
      self.builtinTools = builtinTools
      self.eventMessages = eventMessages
      self.timeouts = timeouts
      self.nudges = nudges
      self.webhooks = webhooks
    }
  }
#endif
