// This file is generated by generator.ts
public struct EviPostedNudgeSpec: Codable, Hashable {
  public let enabled: Bool?
  public let intervalSecs: Int?

  public init(
    enabled: Bool?,
    intervalSecs: Int?
  ) {
    self.enabled = enabled
    self.intervalSecs = intervalSecs
  }
}
