// This file is generated by generator.ts
public struct EviPostedLanguageModel: Codable, Hashable {
  public let modelProvider: ModelProviderEnum?
  public let modelResource: LanguageModelType?
  public let temperature: Double?

  public init(
    modelProvider: ModelProviderEnum?,
    modelResource: LanguageModelType?,
    temperature: Double?
  ) {
    self.modelProvider = modelProvider
    self.modelResource = modelResource
    self.temperature = temperature
  }
}
