// This file is generated by generator.ts
public struct EviPostedEllmModel: Codable, Hashable {
  public let allowShortResponses: Bool?

  public init(allowShortResponses: Bool?) {
    self.allowShortResponses = allowShortResponses
  }
}
