// This file is generated by generator.ts
public struct EviPostedUserDefinedToolSpec: Codable, Hashable {
  public let id: String
  public let version: Int?

  public init(
    id: String,
    version: Int?
  ) {
    self.id = id
    self.version = version
  }
}
