// This file is generated by generator.ts
#if HUME_SERVER
  public struct EviReturnBuiltinTool: Codable, Hashable {
    public let toolType: tool_type
    public let name: String
    public let fallbackContent: String?
  }
#endif
