// This file is generated by generator.ts
public struct EviReturnLanguageModel: Codable, Hashable {
  public let modelProvider: ModelProviderEnum?
  public let modelResource: LanguageModelType?
  public let temperature: Double?
}
