// This file is generated by generator.ts
#if HUME_SERVER
  public struct EviReturnPagedConfigs: Codable, Hashable {
    public let pageNumber: Int?
    public let pageSize: Int?
    public let totalPages: Int
    public let configsPage: [EviReturnConfig]?
  }
#endif
