// This file is generated by generator.ts
#if HUME_SERVER
  public struct EviReturnTimeoutSpecs: Codable, Hashable {
    public let inactivity: EviReturnTimeoutSpec
    public let maxDuration: EviReturnTimeoutSpec
  }
#endif
