// This file is generated by generator.ts
public struct EviReturnUserDefinedTool: Codable, Hashable {
  public let toolType: tool_type
  public let id: String
  public let version: Int
  public let versionType: version_type
  public let versionDescription: String?
  public let name: String
  public let createdOn: Int
  public let modifiedOn: Int
  public let fallbackContent: String?
  public let description: String?
  public let parameters: String
}
