// This file is generated by generator.ts
#if HUME_SERVER
  public struct EviReturnConfig: Codable, Hashable {
    public let name: String?
    public let id: String?
    public let version: Int?
    public let tools: [EviReturnUserDefinedTool]?
    public let versionDescription: String?
    public let languageModel: EviReturnLanguageModel?
    public let builtinTools: [EviReturnBuiltinTool]?
    public let eviVersion: String?
    public let timeouts: EviReturnTimeoutSpecs?
    public let nudges: EviReturnNudgeSpec?
    public let eventMessages: EviReturnEventMessageSpecs?
    public let ellmModel: EviReturnEllmModel?
    public let voice: EviReturnVoice?
    public let prompt: EviReturnPrompt?
    public let webhooks: [ReturnWebhookSpec]?
    public let createdOn: Int?
    public let modifiedOn: Int?
  }
#endif
