// This file is generated by generator.ts
public struct EviReturnEventMessageSpecs: Codable, Hashable {
  public let onNewChat: EviReturnEventMessageSpec?
  public let onInactivityTimeout: EviReturnEventMessageSpec?
  public let onMaxDurationTimeout: EviReturnEventMessageSpec?
}
