// This file is generated by generator.ts
#if HUME_SERVER
  public struct EviReturnVoice: Codable, Hashable {
    public let id: String?
    public let name: String?
    public let provider: Provider?
  }
#endif
