// This file is generated by generator.ts
#if HUME_SERVER
  import Foundation

  public enum EviVoiceRef: Codable, Hashable {
    case voiceId(VoiceId)
    case voiceName(VoiceName)

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let voiceId = try? container.decode(VoiceId.self) {
        self = .voiceId(voiceId)
      } else if let voiceName = try? container.decode(VoiceName.self) {
        self = .voiceName(voiceName)
      } else {
        throw DecodingError.typeMismatch(
          EviVoiceRef.self,
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Invalid value for EviVoiceRef"
          )
        )
      }
    }
  }

#endif
