// This file is generated by generator.ts
#if HUME_SERVER
  public struct Inactivity: Codable, Hashable {
    public let durationSecs: Int?
    public let enabled: Bool

    public init(
      durationSecs: Int?,
      enabled: Bool
    ) {
      self.durationSecs = durationSecs
      self.enabled = enabled
    }
  }
#endif
