// This file is generated by generator.ts
public struct MaxDuration: Codable, Hashable {
  public let durationSecs: Int?
  public let enabled: Bool

  public init(
    durationSecs: Int?,
    enabled: Bool
  ) {
    self.durationSecs = durationSecs
    self.enabled = enabled
  }
}
