// This file is generated by generator.ts
public struct MillisecondInterval: Codable {
  public let begin: Int
  public let end: Int

  public init(begin: Int, end: Int) {
    self.begin = begin
    self.end = end
  }
}
