// This file is generated by generator.ts
#if HUME_SERVER

  public enum ModelProviderEnum: String, Codable {
    case groq = "GROQ"
    case openAi = "OPEN_AI"
    case fireworks = "FIREWORKS"
    case anthropic = "ANTHROPIC"
    case customLanguageModel = "CUSTOM_LANGUAGE_MODEL"
    case google = "GOOGLE"
    case humeAi = "HUME_AI"
    case amazonBedrock = "AMAZON_BEDROCK"
    case perplexity = "PERPLEXITY"
    case sambanova = "SAMBANOVA"
    case cerebras = "CEREBRAS"
  }

#endif
