// This file is generated by generator.ts
#if HUME_SERVER
  public struct PostedEventMessageSpecs: Codable, Hashable {
    public let onNewChat: PostedEventMessageSpec?
    public let onInactivityTimeout: PostedEventMessageSpec?
    public let onMaxDurationTimeout: PostedEventMessageSpec?

    public init(
      onNewChat: PostedEventMessageSpec?,
      onInactivityTimeout: PostedEventMessageSpec?,
      onMaxDurationTimeout: PostedEventMessageSpec?
    ) {
      self.onNewChat = onNewChat
      self.onInactivityTimeout = onInactivityTimeout
      self.onMaxDurationTimeout = onMaxDurationTimeout
    }
  }
#endif
