// This file is generated by generator.ts
#if HUME_SERVER
  public struct PostedEllmModel: Codable, Hashable {
    public let allowShortResponses: Bool?

    public init(allowShortResponses: Bool?) {
      self.allowShortResponses = allowShortResponses
    }
  }
#endif
