// This file is generated by generator.ts
#if HUME_SERVER
  public struct PostedTimeoutSpecs: Codable, Hashable {
    public let inactivity: Inactivity?
    public let maxDuration: MaxDuration?

    public init(
      inactivity: Inactivity?,
      maxDuration: MaxDuration?
    ) {
      self.inactivity = inactivity
      self.maxDuration = maxDuration
    }
  }
#endif
