// This file is generated by generator.ts
#if HUME_SERVER
  public struct PostedBuiltinTool: Codable, Hashable {
    public let name: name
    public let fallbackContent: String?

    public init(
      name: name,
      fallbackContent: String?
    ) {
      self.name = name
      self.fallbackContent = fallbackContent
    }
  }
#endif
