// This file is generated by generator.ts
#if HUME_SERVER
  public struct PostedConfigName: Codable, Hashable {
    public let name: String

    public init(name: String) {
      self.name = name
    }
  }
#endif
