// This file is generated by generator.ts
#if HUME_SERVER
  public struct PostedConfigVersionDescription: Codable, Hashable {
    public let versionDescription: String?

    public init(versionDescription: String?) {
      self.versionDescription = versionDescription
    }
  }
#endif
