// This file is generated by generator.ts
#if HUME_SERVER
  public struct PostedConfigVersion: Codable, Hashable {
    public let eviVersion: String
    public let versionDescription: String?
    public let prompt: PostedConfigPromptSpec?
    public let voice: VoiceRef?
    public let languageModel: PostedLanguageModel?
    public let ellmModel: PostedEllmModel?
    public let tools: [PostedUserDefinedToolSpec]?
    public let builtinTools: [PostedBuiltinTool]?
    public let eventMessages: PostedEventMessageSpecs?
    public let timeouts: PostedTimeoutSpecs?
    public let nudges: PostedNudgeSpec?
    public let webhooks: [PostedWebhookSpec]?

    public init(
      eviVersion: String,
      versionDescription: String?,
      prompt: PostedConfigPromptSpec?,
      voice: VoiceRef?,
      languageModel: PostedLanguageModel?,
      ellmModel: PostedEllmModel?,
      tools: [PostedUserDefinedToolSpec]?,
      builtinTools: [PostedBuiltinTool]?,
      eventMessages: PostedEventMessageSpecs?,
      timeouts: PostedTimeoutSpecs?,
      nudges: PostedNudgeSpec?,
      webhooks: [PostedWebhookSpec]?
    ) {
      self.eviVersion = eviVersion
      self.versionDescription = versionDescription
      self.prompt = prompt
      self.voice = voice
      self.languageModel = languageModel
      self.ellmModel = ellmModel
      self.tools = tools
      self.builtinTools = builtinTools
      self.eventMessages = eventMessages
      self.timeouts = timeouts
      self.nudges = nudges
      self.webhooks = webhooks
    }
  }
#endif
