// This file is generated by generator.ts
public struct ResumeAssistantMessage: Encodable {
  public let customSessionId: String?
  public let type: String

  public init(customSessionId: String?, type: String) {
    self.customSessionId = customSessionId
    self.type = type
  }
}
