// This file is generated by generator.ts
public struct ReturnPrompt: Codable, Hashable {
  public let id: String
  public let version: Int
  public let versionType: String
  public let versionDescription: String?
  public let name: String
  public let createdOn: Int
  public let modifiedOn: Int
  public let text: String
}
