// This file is generated by generator.ts
#if HUME_SERVER
  public struct ReturnPrompt: Codable, Hashable {
    public let name: String
    public let id: String
    public let text: String
    public let version: Int
    public let versionDescription: String?
    public let versionType: version_type
    public let createdOn: Int
    public let modifiedOn: Int
  }
#endif
