// This file is generated by generator.ts
#if HUME_SERVER
  public struct ReturnTimeoutSpecs: Codable, Hashable {
    public let inactivity: ReturnTimeoutSpec
    public let maxDuration: ReturnTimeoutSpec
  }
#endif
