// This file is generated by generator.ts
#if HUME_SERVER
  public struct ReturnLanguageModel: Codable, Hashable {
    public let modelProvider: ModelProviderEnum?
    public let modelResource: LanguageModelType?
    public let temperature: Double?
  }
#endif
