// This file is generated by generator.ts
#if HUME_SERVER
  public struct ReturnEventMessageSpecs: Codable, Hashable {
    public let onNewChat: ReturnEventMessageSpec?
    public let onInactivityTimeout: ReturnEventMessageSpec?
    public let onMaxDurationTimeout: ReturnEventMessageSpec?
  }
#endif
