// This file is generated by generator.ts
public struct ReturnConfig: Codable, Hashable {
  public let id: String?
  public let version: Int?
  public let eviVersion: String?
  public let versionDescription: String?
  public let name: String?
  public let createdOn: Int?
  public let modifiedOn: Int?
  public let prompt: ReturnPrompt?
  public let voice: EviReturnVoice?
  public let languageModel: EviReturnLanguageModel?
  public let ellmModel: EviReturnEllmModel?
  public let tools: [EviReturnUserDefinedTool]?
  public let builtinTools: [EviReturnBuiltinTool]?
  public let eventMessages: EviReturnEventMessageSpecs?
  public let timeouts: EviReturnTimeoutSpecs?
  public let nudges: EviReturnNudgeSpec?
  public let webhooks: [ReturnWebhookSpec]?
}
