// This file is generated by generator.ts
#if HUME_SERVER
  public struct ReturnConfig: Codable, Hashable {
    public let name: String?
    public let id: String?
    public let version: Int?
    public let tools: [ReturnUserDefinedTool]?
    public let versionDescription: String?
    public let languageModel: ReturnLanguageModel?
    public let builtinTools: [ReturnBuiltinTool]?
    public let eviVersion: String?
    public let timeouts: ReturnTimeoutSpecs?
    public let nudges: ReturnNudgeSpec?
    public let eventMessages: ReturnEventMessageSpecs?
    public let ellmModel: ReturnEllmModel?
    public let voice: ReturnVoice?
    public let prompt: ReturnPrompt?
    public let webhooks: [ReturnWebhookSpec]?
    public let createdOn: Int?
    public let modifiedOn: Int?
  }
#endif
