// This file is generated by generator.ts
public struct SessionSettings: Codable, Hashable {
  public let type: String
  public let customSessionId: String?
  public let systemPrompt: String?
  public let context: Context?
  public let audio: AudioConfiguration?
  public let languageModelApiKey: String?
  public let tools: [Tool]?
  public let builtinTools: [BuiltinToolConfig]?

  public init(
    audio: AudioConfiguration?,
    builtinTools: [BuiltinToolConfig]?,
    context: Context?,
    customSessionId: String?,
    languageModelApiKey: String?,
    systemPrompt: String?,
    tools: [Tool]?
  ) {
    self.audio = audio
    self.builtinTools = builtinTools
    self.context = context
    self.customSessionId = customSessionId
    self.languageModelApiKey = languageModelApiKey
    self.systemPrompt = systemPrompt
    self.tools = tools
    self.type = "session_settings"
  }
}
