// This file is generated by generator.ts
public struct SessionSettings: Codable {
  public let audio: AudioConfiguration?
  public let builtinTools: [BuiltinToolConfig]?
  public let context: TODO_IGNORED_TYPE?
  public let customSessionId: String?
  public let languageModelApiKey: String?
  public let systemPrompt: String?
  public let tools: [Tool]?
  public let type: String

  public init(
    audio: AudioConfiguration?, builtinTools: [BuiltinToolConfig]?, context: TODO_IGNORED_TYPE?,
    customSessionId: String?, languageModelApiKey: String?, systemPrompt: String?, tools: [Tool]?,
    type: String
  ) {
    self.audio = audio
    self.builtinTools = builtinTools
    self.context = context
    self.customSessionId = customSessionId
    self.languageModelApiKey = languageModelApiKey
    self.systemPrompt = systemPrompt
    self.tools = tools
    self.type = type
  }
}
