// This file is generated by generator.ts
public struct ToolResponseMessage: Encodable {
  public let content: String
  public let customSessionId: String?
  public let toolCallId: String
  public let toolName: String?
  public let toolType: ToolType?
  public let type: String

  public init(
    content: String, customSessionId: String?, toolCallId: String, toolName: String?,
    toolType: ToolType?, type: String
  ) {
    self.content = content
    self.customSessionId = customSessionId
    self.toolCallId = toolCallId
    self.toolName = toolName
    self.toolType = toolType
    self.type = type
  }
}
