// This file is generated by generator.ts
public struct UserInput: Codable, Hashable {
  public let type: String
  public let customSessionId: String?
  public let text: String

  public init(
    customSessionId: String?,
    text: String
  ) {
    self.customSessionId = customSessionId
    self.text = text
    self.type = "user_input"
  }
}
