// This file is generated by generator.ts
public struct UserInput: Codable {
  public let customSessionId: String?
  public let text: String
  public let type: String

  public init(customSessionId: String?, text: String, type: String) {
    self.customSessionId = customSessionId
    self.text = text
    self.type = type
  }
}
