// This file is generated by generator.ts
public struct UserMessage: Codable {
  public let customSessionId: String?
  public let fromText: Bool
  public let interim: Bool
  public let message: ChatMessage
  public let models: Inference
  public let time: MillisecondInterval
  public let type: String

  public init(
    customSessionId: String?, fromText: Bool, interim: Bool, message: ChatMessage,
    models: Inference, time: MillisecondInterval, type: String
  ) {
    self.customSessionId = customSessionId
    self.fromText = fromText
    self.interim = interim
    self.message = message
    self.models = models
    self.time = time
    self.type = type
  }
}
