// This file is generated by generator.ts
#if HUME_SERVER
  public struct VoiceName: Codable, Hashable {
    public let name: String
    public let provider: Provider?

    public init(
      name: String,
      provider: Provider?
    ) {
      self.name = name
      self.provider = provider
    }
  }
#endif
