// This file is generated by generator.ts
#if HUME_SERVER
  public struct VoiceId: Codable, Hashable {
    public let id: String
    public let provider: Provider?

    public init(
      id: String,
      provider: Provider?
    ) {
      self.id = id
      self.provider = provider
    }
  }
#endif
