// This file is generated by generator.ts
public struct WebSocketError: Codable {
  public let code: String
  public let customSessionId: String?
  public let message: String
  public let requestId: String?
  public let slug: String
  public let type: String

  public init(
    code: String, customSessionId: String?, message: String, requestId: String?, slug: String,
    type: String
  ) {
    self.code = code
    self.customSessionId = customSessionId
    self.message = message
    self.requestId = requestId
    self.slug = slug
    self.type = type
  }
}
