// This file is generated by generator.ts
public struct WebSocketError: Codable, Hashable {
  public let type: String
  public let customSessionId: String?
  public let code: String
  public let slug: String
  public let message: String
  public let requestId: String?
}
