//
//  File.swift
//  
//
//  This file was auto-generated by Fern from our API Definition.
//

import Foundation


public class EmpatheticVoice {
    
    private let options: HumeClient.Options
    
    init(options: HumeClient.Options) {
        self.options = options
    }
    
    public lazy var chat: Chat = {
        return Chat(options: options)
    }()
    
    public lazy var chats: Chats = {
        return Chats()
    }()
    
    public lazy var tools: Tools = {
        return Tools()
    }()
    
    public lazy var configs: Configs = {
        return Configs(options: options)
    }()

}
