// This file is generated by generator.ts
public struct AudioEncoding: Codable {
  public let format: AudioFormatType
  public let sampleRate: Int

  public init(format: AudioFormatType, sampleRate: Int) {
    self.format = format
    self.sampleRate = sampleRate
  }
}
