// This file is generated by generator.ts

public enum Format: Encodable {
  case todo(TODO)
  case todo(TODO)
  case todo(TODO)

  private enum CodingKeys: String, CodingKey {
    case type
  }

  public func encode(to encoder: Encoder) throws {
    // Implement encoding logic as needed.
  }
}
