// This file is generated by generator.ts
public struct PostedTts: Encodable {
  public let context: TODO_UNIONOFREFS_TYPE?
  public let format: Format?
  public let numGenerations: Int?
  public let splitUtterances: Bool?
  public let stripHeaders: Bool?
  public let utterances: [PostedUtterance]
  public let instantMode: Bool?

  public init(
    context: TODO_UNIONOFREFS_TYPE?, format: Format?, numGenerations: Int?, splitUtterances: Bool?,
    stripHeaders: Bool?, utterances: [PostedUtterance], instantMode: Bool?
  ) {
    self.context = context
    self.format = format
    self.numGenerations = numGenerations
    self.splitUtterances = splitUtterances
    self.stripHeaders = stripHeaders
    self.utterances = utterances
    self.instantMode = instantMode
  }
}
