// This file is generated by generator.ts
public struct PostedTts: Codable, Hashable {
  public let context: PostedTtsContext?
  public let utterances: [PostedUtterance]
  public let numGenerations: Int?
  public let format: Format?
  public let splitUtterances: Bool?
  public let stripHeaders: Bool?
  public let instantMode: Bool?

  public init(
    context: PostedTtsContext?,
    numGenerations: Int?,
    splitUtterances: Bool?,
    stripHeaders: Bool?,
    utterances: [PostedUtterance],
    instantMode: Bool?,
    format: Format?
  ) {
    self.context = context
    self.numGenerations = numGenerations
    self.splitUtterances = splitUtterances
    self.stripHeaders = stripHeaders
    self.utterances = utterances
    self.instantMode = instantMode
    self.format = format
  }
}
