// This file is generated by generator.ts
public struct PostedUtteranceVoiceWithId: Codable {
  public let id: String
  public let provider: VoiceProvider?

  public init(id: String, provider: VoiceProvider?) {
    self.id = id
    self.provider = provider
  }
}
