// This file is generated by generator.ts
public struct PostedUtteranceVoiceWithName: Codable {
  public let name: String
  public let provider: VoiceProvider?

  public init(name: String, provider: VoiceProvider?) {
    self.name = name
    self.provider = provider
  }
}
