// This file is generated by generator.ts
public struct PostedVoice: Encodable {
  public let generationId: String
  public let name: String

  public init(generationId: String, name: String) {
    self.generationId = generationId
    self.name = name
  }
}
