// This file is generated by generator.ts
public struct PostedUtterance: Codable, Hashable {
  public let description: String?
  public let speed: Double?
  public let text: String
  public let trailingSilence: Double?
  public let voice: PostedUtteranceVoice?

  public init(
    description: String?,
    speed: Double?,
    trailingSilence: Double?,
    text: String,
    voice: PostedUtteranceVoice?
  ) {
    self.description = description
    self.speed = speed
    self.trailingSilence = trailingSilence
    self.text = text
    self.voice = voice
  }
}
