// This file is generated by generator.ts
public struct PostedUtterance: Codable {
  public let description: String?
  public let speed: Double?
  public let text: String
  public let trailingSilence: Double?
  public let voice: TODO_UNIONOFREFS_TYPE?

  public init(
    description: String?, speed: Double?, text: String, trailingSilence: Double?,
    voice: TODO_UNIONOFREFS_TYPE?
  ) {
    self.description = description
    self.speed = speed
    self.text = text
    self.trailingSilence = trailingSilence
    self.voice = voice
  }
}
