// This file is generated by generator.ts
public struct ReturnVoice: Codable {
  public let id: String?
  public let name: String?
  public let provider: VoiceProvider?

  public init(id: String?, name: String?, provider: VoiceProvider?) {
    self.id = id
    self.name = name
    self.provider = provider
  }
}
