// This file is generated by generator.ts
public struct ReturnPagedVoices: Decodable {
  public let pageNumber: Int?
  public let pageSize: Int?
  public let totalPages: Int?
  public let voicesPage: [ReturnVoice]?
}
