// This file is generated by generator.ts
public struct ReturnGeneration: Codable {
  public let audio: String
  public let duration: Double
  public let encoding: AudioEncoding
  public let fileSize: Int
  public let generationId: String
  public let snippets: [[Snippet]]

  public init(
    audio: String, duration: Double, encoding: AudioEncoding, fileSize: Int, generationId: String,
    snippets: [[Snippet]]
  ) {
    self.audio = audio
    self.duration = duration
    self.encoding = encoding
    self.fileSize = fileSize
    self.generationId = generationId
    self.snippets = snippets
  }
}
