// This file is generated by generator.ts
public struct SnippetAudioChunk: Codable {
  public let audio: String
  public let chunkIndex: Int
  public let generationId: String
  public let isLastChunk: Bool
  public let snippetId: String
  public let text: String
  public let transcribedText: String?
  public let utteranceIndex: Int?

  public init(
    audio: String, chunkIndex: Int, generationId: String, isLastChunk: Bool, snippetId: String,
    text: String, transcribedText: String?, utteranceIndex: Int?
  ) {
    self.audio = audio
    self.chunkIndex = chunkIndex
    self.generationId = generationId
    self.isLastChunk = isLastChunk
    self.snippetId = snippetId
    self.text = text
    self.transcribedText = transcribedText
    self.utteranceIndex = utteranceIndex
  }
}
