// This file is generated by generator.ts
public struct SnippetAudioChunk: Codable, Hashable {
  public let generationId: String
  public let snippetId: String
  public let text: String
  public let transcribedText: String?
  public let chunkIndex: Int
  public let audio: String
  public let audioFormat: AudioFormatType
  public let isLastChunk: Bool
  public let utteranceIndex: Int?
  public let snippet: Snippet?
}
