// This file is generated by generator.ts
public struct Snippet: Codable {
  public let audio: String
  public let generationId: String
  public let id: String
  public let text: String
  public let transcribedText: String?
  public let utteranceIndex: Int?

  public init(
    audio: String, generationId: String, id: String, text: String, transcribedText: String?,
    utteranceIndex: Int?
  ) {
    self.audio = audio
    self.generationId = generationId
    self.id = id
    self.text = text
    self.transcribedText = transcribedText
    self.utteranceIndex = utteranceIndex
  }
}
