// This file is generated by generator.ts
public struct SnippetAudioChunk: Codable, Hashable {
  public let audio: String
  public let audioFormat: AudioFormatType
  public let chunkIndex: Int
  public let generationId: String
  public let isLastChunk: Bool
  public let requestId: String
  public let snippet: SnippetInput?
  public let snippetId: String
  public let text: String
  public let transcribedText: String?
  public let type: String
  public let utteranceIndex: Int?
}
