// This file is generated by generator.ts
public struct TimestampMessage: Codable, Hashable {
  public let generationId: String
  public let requestId: String
  public let snippetId: String
  public let timestamp: Timestamp
  public let type: String
}
