// This file is generated by generator.ts

public enum TtsOutput: Codable, Hashable {
  case snippetAudioChunk(SnippetAudioChunk)
  case timestampMessage(TimestampMessage)

  private enum CodingKeys: String, CodingKey {
    case type
  }
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    let typeValue = try container.decode(String.self, forKey: .type)
    switch typeValue {
    case "audio": self = .snippetAudioChunk(try SnippetAudioChunk(from: decoder))
    case "timestamp": self = .timestampMessage(try TimestampMessage(from: decoder))
    default:
      throw DecodingError.dataCorruptedError(
        forKey: .type, in: container, debugDescription: "Unexpected type value: \(typeValue)")
    }
  }
  public func encode(to encoder: Encoder) throws {
    switch self {
    case .snippetAudioChunk(let value): try value.encode(to: encoder)
    case .timestampMessage(let value): try value.encode(to: encoder)
    }
  }
}
