// This file is generated by generator.ts

import Foundation

public class Tts {

  private let options: HumeClient.Options

  init(options: HumeClient.Options) {
    self.options = options
  }
  public lazy var tts: TTS = { TTS(options: options) }()
  public lazy var voices: Voices = { Voices(options: options) }()
}
