// This file is generated by generator.ts

import Foundation

public class EmpathicVoiceClient {

  private let networkClient: NetworkClient

  init(networkClient: NetworkClient) {
    self.networkClient = networkClient
  }
  public lazy var configs: Configs = { Configs(networkClient: networkClient) }()
}
