// This file is generated by generator.ts

import Foundation

public class EmpathicVoiceClient {

  private let options: HumeClient.Options
  private let networkClient: NetworkClient

  init(networkClient: NetworkClient, options: HumeClient.Options) {
    self.networkClient = networkClient
    self.options = options
  }

  public lazy var chat: Chat = { Chat(options: options) }()

  public lazy var configs: Configs = { Configs(networkClient: networkClient) }()
}
