name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Swift Format
      run: |
        brew install swift-format
    
    - name: Check Swift formatting
      run: |
        # Run swift format and capture output
        swift format . --recursive --in-place
        
        # Check if there are any changes
        if ! git diff --exit-code; then
          echo "❌ Swift formatting check failed!"
          echo "The following files need formatting:"
          git diff --name-only
          echo ""
          echo "Please run 'swift format . --recursive --in-place' and commit the changes."
          exit 1
        else
          echo "✅ All Swift files are properly formatted!"
        fi

  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer

    - name: Create Simulator
      run: |
        xcrun simctl create "HumeTestiPhone" com.apple.CoreSimulator.SimDeviceType.iPhone-16-Pro

    - name: Boot Simulator
      run: |
        UDID=$(xcrun simctl list devices | grep "HumeTestiPhone" | awk -F'[()]' '{print $2}')
        xcrun simctl boot $UDID
    
    - name: Build for iOS device
      run: |
        swift build --triple arm64-apple-ios --sdk $(xcrun --sdk iphoneos --show-sdk-path)
        
    - name: Run tests on iOS Simulator
      run: |
        xcodebuild test -scheme Hume-Package -destination 'platform=iOS Simulator,name=HumeTestiPhone'

    - name: Lint podspec
      run: |
        pod lib lint --allow-warnings