name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      
    - name: Show Xcode and Swift versions
      run: |
        xcodebuild -version
        swift --version
        
    - name: Build for iOS
      run: swift build --triple arm64-apple-ios --sdk $(xcrun --sdk iphoneos --show-sdk-path)
      
    - name: Build for iOS Simulator  
      run: swift build --triple arm64-apple-ios-simulator --sdk $(xcrun --sdk iphonesimulator --show-sdk-path)
      
    - name: List available simulators
      run: xcrun simctl list devices available
      
    - name: Run tests using xcodebuild
      run: |
        xcodebuild test \
          -scheme Hume \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -enableCodeCoverage NO \
          CODE_SIGNING_ALLOWED=NO